### ISSUE TITLE
Documentation update for infrastructure agent in Docker environment

### ISSUE THREAD

**Issue by gitrequests** [newrelic/nri-nginx#108]
The infrastructure agent can be run in a Docker environment. This is described in the documentation: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent/.

The documentation does not describe how to install the integration for NGINX in docker.

If we create nginx-config.yml and run the container, we will see an error:
`level=warning msg="can't instantiate integrations from file" component=integrations.Manager error="can't instantiate integration: can't find an executable given the name: nri-nginx" file=/etc/newrelic-infra/integrations.d/nginx-config.yml
`

The error tells us that the integration needs to be installed first.

The newrelic/infrastructure docker image is based on Alpine linux. You can verify this by typing in the terminal:

`cat /etc/os-release`

```bash
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.0
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

Alpine linux uses the APK package manager and does not have the nri-nginx package in the repositories.

If this package were in the repository, then it would be possible to build a Docker image like this:
```yml
FROM newrelic/infrastructure:latest
ADD newrelic-infra.yml /etc/newrelic-infra.yml
ADD nginx-config.yml /etc/newrelic-infra/integrations.d/nginx-config.yml
RUN apk add nri-nginx
```

There are many examples with building a docker image here: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/container-infrastructure-monitoring/

If I understand correctly, in Alpine linux we need to build the package from source.

**Could you add an example to the documentation on how to properly install and use the NGINX integration for Alpine linux and docker in particular?**

**Comment by gitrequests** [comment]
The problem was solved using a different image that contains the necessary integrations.

newrelic/infrastructure-bundle instead of newrelic/infrastructure
https://hub.docker.com/r/newrelic/infrastructure-bundle

**Comment by Winfle** [comment]
Still actual issue.
I need to have it working with Nginx runinng in Alpine container
@gitrequests Did you find some solution to get this sorted? Thanks
