### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by AlexMouton** [newrelic/nri-nginx#12]
Hi Folks!

Read me hints at installing from 'archive files' but I don't see any.
Am I missing something?

naive `apt-get install nri-nginx` also seems to fail which is the recommendation from the nginx notes.

Thanks
Alex

**Comment by xino12** [comment]
Hi Alex,

in which OS are you trying to install the integration?
The binary should be in: ` /var/db/newrelic-infra/newrelic-integrations/bin/nr-nginx`

Let me know if you see the binary there.

**Comment by AlexMouton** [comment]
Hi
I think I see my misunderstaning.
I'm working in kubernetes so I have newrelic-infra deployed separately from my nginx pods. 
I was expecting I would install nr-nginx adjacent to nginx but it should be adjacent newrelic-infra.
infra has all the keys set up to install nr-nginx just fine.

Now to figure out how to point it at these dynamic pods.

Thanks
A

**Comment by xino12** [comment]
Right now we don't have a nice way to do that yet, but we're working on an easy way to use our infrastructure integrations inside kubernetes, I'll let you know once we have that available.

**Comment by RafaelAybar** [comment]
@AlexMouton @xino12 i am also trying to deploy the nginx agent in Kuberbetes, but first, i am trying to monitor a local nginx service, but i am  not able  to do it properly.

Docker logs
```
[WARN  tini (6)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
[FATAL tini (7)] exec /usr/bin/newrelic-infra-service failed: No such file or directory
```
