### ISSUE TITLE
No documentation for Kubernetes / docker agent

### ISSUE THREAD

**Issue by RafaelAybar** [newrelic/nri-nginx#41]
Hi, can you improve the documentation for nginx agent installation for docker and Kubernetes, please?
I think that an example it is enough.

**Comment by ardias** [comment]
Hi @RafaelAybar 
have you checked the official New Relic docuemntation here https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config and here https://docs.newrelic.com/docs/integrations/kubernetes-integration/link-apps-services/monitor-services-running-kubernetes ?

If that's not enough, what is exactly the issue you are facing?

**Comment by RafaelAybar** [comment]
Yes, i did
