### ISSUE TITLE
No documentation for endpoints option 

### ISSUE THREAD

**Issue by aplaza1** [newrelic/nri-nginx#51]
Hi, the sample config file has a `endpoints` config option: https://github.com/newrelic/nri-nginx/blob/4563398f1bd103c01173c42618fe394f2cfba8a4/nginx-config.yml.sample#L11

However, the official [nri-nginx New Relic documentation](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config) does not mention this option. Is it possible to update the documentation to understand how to set up the `endpoints` config option and what it does?

**Comment by ardias** [comment]
Hi @aplaza1! Thank you for reporting that.

We indeed at some point supported that option but we hadn't documented it yet and have since found out that it was not working as expected. This is a "bug" in the configuration sample as the option is no longer supported.

**Comment by gsanchezgavier** [comment]
Hi @aplaza1 , We have released a new version where the custom endpoints configuration is no longer supported. 
And updated the [New Relic documentation](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config)
