### ISSUE TITLE
No Reference To The Metrics That Are Created

### ISSUE THREAD

**Issue by jake-codes** [newrelic/nri-nginx#86]
Customers do not know whether it is worth it or not to install this integration if we do not show them the metrics that are captured out of the box.

I see the link to the docs website but we cannot outsource this completely to the documentation team. The docs teams may be able to add additional bells and whistles sometimes, but engineers who are searching for nginx and new relic will not want to be taken to several different pages to learn how to see what the benefits are of the integration and how long it will take to install and configure. 

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by mangulonr** [comment]
Hi @jake-codes
