### ISSUE TITLE
net.requestsPerSecond in NginxSample does not handle nginx restart

### ISSUE THREAD

**Issue by cc32d9** [newrelic/nri-nginx#87]
the graph is defined as 

```
SELECT average(net.requestsPerSecond) FROM NginxSample WHERE host LIKE '%cust-XXX-%' TIMESERIES FACET `host` LIMIT 10 SINCE 259200 seconds ago EXTRAPOLATE
```

once an nginx process restarted, the graph went down to minus 35k. Obviously the request counter restarted form 0 and the agent did not detect that. It should detect such occasions and simply reset its own counter.

**Comment by gsanchezgavier** [comment]
Thanks for submitting this @cc32d9, we have addressed the bug and the integration is being released.
